# This rule is not used by the project secretderiver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over secretderiver.lightjack.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secretderiver
    app.kubernetes.io/managed-by: kustomize
  name: derivedsecret-admin-role
rules:
- apiGroups:
  - secretderiver.lightjack.de
  resources:
  - derivedsecrets
  verbs:
  - '*'
- apiGroups:
  - secretderiver.lightjack.de
  resources:
  - derivedsecrets/status
  verbs:
  - get
