apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secretderiver.fullname" . }}-derivedsecret-admin-role
  labels:
  {{- include "secretderiver.labels" . | nindent 4 }}
rules:
- apiGroups:
  - secretderiver.lightjack.de
  resources:
  - derivedsecrets
  verbs:
  - '*'
- apiGroups:
  - secretderiver.lightjack.de
  resources:
  - derivedsecrets/status
  verbs:
  - get
